const PROPERTIES_DATA = [
  {
    id: "sumadhura-solace-whitefield",
    slug: "sumadhura-solace-whitefield",
    name: "Sumadhura Solace",
    developer: "Sumadhura Infracon",
    location: "Whitefield",
    sublocation: "Thubarahalli, Whitefield",
    priceRange: "₹2.18 – 3.10 Cr",
    minPrice: 2.18,
    maxPrice: 3.10,
    config: "3 & 4 BHK",
    configTypes: ["3 BHK", "4 BHK"],
    sizeRange: "1,705 – 2,730 sq.ft.",
    possession: "Possession: Dec 2029",
    possessionYear: 2029,
    possessionCategory: "4+ Years",
    score: 3.9,
    verdict: "Strong End-Use Pick",
    heroImg: "/style-guide/assets/sumadhura_solace_hero_day_aerial.webp",
    url: "/property/sumadhura-solace-whitefield/"
  },
  {
    id: "sumadhura-folium-whitefield",
    slug: "sumadhura-folium-whitefield",
    name: "Sumadhura Folium",
    developer: "Sumadhura Infracon",
    location: "Whitefield",
    sublocation: "Borewell Road, Whitefield",
    priceRange: "₹2.45 – 4.04 Cr",
    minPrice: 2.45,
    maxPrice: 4.04,
    config: "3 & 4 BHK",
    configTypes: ["3 BHK", "4 BHK"],
    sizeRange: "1,470 – 2,425 sq.ft.",
    possession: "Possession: Mar 2028",
    possessionYear: 2028,
    possessionCategory: "2–4 Years",
    score: 3.9,
    verdict: "Core Whitefield + Metro-led Family Living",
    heroImg: "/style-guide/assets/folium/sumadhura_folium_hero_pool_aerial_wide.webp",
    url: "/property/sumadhura-folium-whitefield/"
  },
  {
    id: "sattva-songbird-budigere-road",
    slug: "sattva-songbird-budigere-road",
    name: "Sattva Songbird",
    developer: "Sattva Group",
    location: "Budigere Road",
    sublocation: "Cheemasandra, Budigere Road",
    priceRange: "₹0.72 – 2.67 Cr",
    minPrice: 0.72,
    maxPrice: 2.67,
    config: "Studio, 1, 2, 2.5 & 3 BHK",
    configTypes: ["1 BHK", "2 BHK", "3 BHK"],
    sizeRange: "470 – 1,845 sq.ft.",
    possession: "Possession: May 2029",
    possessionYear: 2029,
    possessionCategory: "4+ Years",
    score: 3.2,
    verdict: "Mixed-Format Living on Budigere Road",
    heroImg: "/style-guide/assets/songbird/sattva_songbird_hero_elevation_day.webp",
    url: "/property/sattva-songbird-budigere-road/"
  },
  {
    id: "sattva-bliss-budigere-cross",
    slug: "sattva-bliss-budigere-cross",
    name: "Sattva Bliss",
    developer: "Sattva Group",
    location: "Budigere Cross",
    sublocation: "Budigere Cross, NH75",
    priceRange: "₹0.66 – 1.14 Cr",
    minPrice: 0.66,
    maxPrice: 1.14,
    config: "1, 2 & 3 BHK",
    configTypes: ["1 BHK", "2 BHK", "3 BHK"],
    sizeRange: "540 – 980 sq.ft.",
    possession: "Possession: Aug 2027",
    possessionYear: 2027,
    possessionCategory: "1–2 Years",
    score: 3.4,
    verdict: "Compact Community Living at Budigere",
    heroImg: "/style-guide/assets/bliss/sattva_bliss_hero_pool_elevation.webp",
    url: "/property/sattva-bliss-budigere-cross/"
  },
  {
    id: "prestige-evergreen-raintree-park",
    slug: "prestige-evergreen-raintree-park",
    name: "Evergreen at Prestige Raintree Park",
    developer: "Prestige Group",
    location: "Varthur",
    sublocation: "Varthur Junction, Whitefield",
    priceRange: "₹1.07 – 4.09 Cr",
    minPrice: 1.07,
    maxPrice: 4.09,
    config: "1, 2, 3, 3.5 & 4 BHK",
    configTypes: ["1 BHK", "2 BHK", "3 BHK", "3.5 BHK", "4 BHK"],
    sizeRange: "650 – 2,500 sq.ft.",
    possession: "Possession: Jun 2030",
    possessionYear: 2030,
    possessionCategory: "4+ Years",
    score: 3.5,
    verdict: "Strong Brand + Township Proposition",
    heroImg: "/style-guide/assets/evergreen/prestige_evergreen_hero_pool_evening.webp",
    url: "/property/prestige-evergreen-raintree-park"
  },
  {
    id: "brigade-belvedere-budigere-cross",
    slug: "brigade-belvedere-budigere-cross",
    name: "Brigade Belvedere",
    developer: "Brigade Group",
    location: "Budigere Cross",
    sublocation: "Budigere Cross, Bengaluru",
    priceRange: "₹0.93 – 2.79 Cr",
    minPrice: 0.93,
    maxPrice: 2.79,
    config: "1, 2 & 3 BHK",
    configTypes: ["1 BHK", "2 BHK", "3 BHK"],
    sizeRange: "620 – 1,780 sq.ft.",
    possession: "Possession: Mar 2031",
    possessionYear: 2031,
    possessionCategory: "4+ Years",
    score: 3.3,
    verdict: "Value-Seeking Homes at Budigere Cross",
    heroImg: "/style-guide/assets/sumadhura_solace_hero_day_aerial.webp",
    url: "/property/brigade-belvedere-budigere-cross/"
  },
  {
    id: "alembic-cloud-forest-alembic-city",
    slug: "alembic-cloud-forest-alembic-city",
    name: "Alembic Cloud Forest at Alembic City",
    developer: "Alembic Real Estate",
    location: "Whitefield",
    sublocation: "Kadugodi / Hope Farm, Whitefield",
    priceRange: "₹2.20 – 3.49 Cr",
    minPrice: 2.20,
    maxPrice: 3.49,
    config: "2, 3 & 3.5 BHK",
    configTypes: ["2 BHK", "3 BHK", "3.5 BHK"],
    sizeRange: "1,310 – 2,180 sq.ft.",
    possession: "Possession: Oct 2029",
    possessionYear: 2029,
    possessionCategory: "2–4 Years",
    score: 3.9,
    verdict: "Integrated City Living",
    heroImg: "/style-guide/assets/sumadhura_solace_hero_day_aerial.webp",
    url: "/property/alembic-cloud-forest-alembic-city/"
  },
  {
    id: "one-residences-sobha-oneworld",
    slug: "one-residences-sobha-oneworld",
    name: "One Residences at SOBHA OneWorld",
    developer: "SOBHA Limited",
    location: "Greater Whitefield",
    sublocation: "OMR / Greater Whitefield",
    priceRange: "₹1.10 – 3.93 Cr",
    minPrice: 1.10,
    maxPrice: 3.93,
    config: "1, 2, 3 & 4 BHK",
    configTypes: ["1 BHK", "2 BHK", "3 BHK", "4 BHK"],
    sizeRange: "680 – 2,650 sq.ft.",
    possession: "Possession: Jul 2032",
    possessionYear: 2032,
    possessionCategory: "4+ Years",
    score: 3.2,
    verdict: "Future Township Scale. Long-Term Bet.",
    heroImg: "/style-guide/assets/sumadhura_solace_hero_day_aerial.webp",
    url: "/property/one-residences-sobha-oneworld/"
  },
  {
    id: "sumadhura-edition-whitefield",
    slug: "sumadhura-edition-whitefield",
    name: "Sumadhura Edition",
    developer: "Sumadhura Infracon",
    location: "Whitefield",
    sublocation: "Siddapura, Core Whitefield",
    priceRange: "₹2.06 – 3.73 Cr",
    minPrice: 2.06,
    maxPrice: 3.73,
    config: "2, 3 & 4 BHK",
    configTypes: ["2 BHK", "3 BHK", "4 BHK"],
    sizeRange: "1,280 – 2,450 sq.ft.",
    possession: "Possession: Dec 2029",
    possessionYear: 2029,
    possessionCategory: "4+ Years",
    score: 3.8,
    verdict: "Premium Core-Whitefield Living",
    heroImg: "/style-guide/assets/edition/sumadhura_edition_hero_towers_day.webp",
    url: "/property/sumadhura-edition-whitefield/"
  },
  {
    id: "sumadhura-capitol-residences",
    slug: "sumadhura-capitol-residences",
    name: "Sumadhura Capitol Residences",
    developer: "Sumadhura Infracon",
    location: "Whitefield",
    sublocation: "Hope Farm / ITPL Road, Whitefield",
    priceRange: "₹2.55 – 3.43 Cr",
    minPrice: 2.55,
    maxPrice: 3.43,
    config: "3 & 4 BHK",
    configTypes: ["3 BHK", "4 BHK"],
    sizeRange: "1,690 – 2,280 sq.ft.",
    possession: "Possession: Dec 2028",
    possessionYear: 2028,
    possessionCategory: "2–4 Years",
    score: 4.0,
    verdict: "Metro-led Convenience + Compact Community",
    heroImg: "/style-guide/assets/capitol/sumadhura_capitol_hero_elevation_day.webp",
    url: "/property/sumadhura-capitol-residences/"
  },
  {
    id: "riviera-uno-whitefield",
    slug: "riviera-uno-whitefield",
    name: "Riviera Uno",
    developer: "Riviera Group",
    location: "Whitefield",
    sublocation: "Soukya Road, Whitefield",
    priceRange: "₹5.25 – 5.30 Cr",
    minPrice: 5.25,
    maxPrice: 5.30,
    config: "4 BHK Ultra-Luxury Villas",
    configTypes: ["4 BHK", "Villas"],
    sizeRange: "3,800 – 4,200 sq.ft.",
    possession: "Possession: Ready to Move",
    possessionYear: 2026,
    possessionCategory: "Ready to Move",
    score: 4.1,
    verdict: "Luxury Villa Proposition",
    heroImg: "/style-guide/assets/riviera/riviera_hero.webp",
    url: "/property/riviera-uno-whitefield/"
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = PROPERTIES_DATA;
}
