/**
 * acre&key Property Data
 * Generated by: Google Sheets → Push to Site
 * Last pushed: NEVER (paste the Apps Script in your sheet to push live data)
 *
 * DO NOT EDIT MANUALLY — edit the Google Sheet instead, then push.
 * NOTE: SEO-critical fields (Title, Canonical, Content) must be hardcoded in HTML.
 */
window.AK_PROPERTY = {
  PRICE_MIN:          "PRICE_MIN",
  PRICE_MAX:          "PRICE_MAX",
  BASE_RATE_MIN:      "BASE_RATE_MIN",
  BASE_RATE_MAX:      "BASE_RATE_MAX",
  VERDICT_SCORE:      "0.00",
  APPRECIATION_CAGR:  "APPRECIATION_CAGR",
  RENTAL_YIELD:       "RENTAL_YIELD",
  LAST_UPDATED:       "LAST_UPDATED"
};

// Inject into DOM (Only for pricing/metrics, safe for SEO)
(function () {
  var d = window.AK_PROPERTY;
  document.querySelectorAll('[data-ak-field]').forEach(function (el) {
    var key = el.getAttribute('data-ak-field');
    if (d[key] !== undefined && d[key] !== '') el.textContent = d[key];
  });
  window.dispatchEvent(new CustomEvent('ak:data:ready', { detail: d }));
})();
